/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'status' : string,
  'name' : string,
  'email' : string,
  'preferredDate' : string,
  'timestamp' : Time,
  'phone' : string,
  'consultationType' : string,
}
export interface CartItem {
  'weight' : string,
  'productId' : string,
  'quantity' : bigint,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'type' : string,
}
export interface Gemstone {
  'id' : string,
  'sanskritName' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : [] | [string],
  'certification' : boolean,
  'price' : bigint,
  'weightOptions' : Array<string>,
}
export interface Review {
  'productId' : string,
  'reviewerName' : string,
  'comment' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export interface SocialMediaLinks {
  'instagram' : string,
  'facebook' : string,
  'youtube' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<[string, ExternalBlob, string], undefined>,
  'addGemstone' : ActorMethod<[Gemstone], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGalleryItem' : ActorMethod<[string], undefined>,
  'deleteGemstone' : ActorMethod<[string], undefined>,
  'getAllBookingRequests' : ActorMethod<[], Array<BookingRequest>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllGemstones' : ActorMethod<[], Array<Gemstone>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[string], Array<CartItem>>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getReviewsByProduct' : ActorMethod<[string], Array<Review>>,
  'getSocialMediaLinks' : ActorMethod<[], SocialMediaLinks>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBookingRequest' : ActorMethod<[BookingRequest], undefined>,
  'submitContactForm' : ActorMethod<[ContactSubmission], undefined>,
  'updateCart' : ActorMethod<[string, Array<CartItem>], undefined>,
  'updateGemstone' : ActorMethod<[Gemstone], undefined>,
  'updateSocialMediaLinks' : ActorMethod<[SocialMediaLinks], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];